# Generated by Django 5.1.2 on 2025-11-12 07:36

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devinette',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField(blank=True)),
                ('image_name', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('reponse', models.CharField(max_length=100)),
                ('date_dispo', models.DateField(default='2025-11-02')),
                ('genre', models.CharField(choices=[('FI', 'Film'), ('CH', 'Chanson'), ('PE', 'Personalité')], default='FI', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('image_name', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('reponse', models.CharField(max_length=100)),
                ('date_dispo', models.DateField(default='2025-11-02')),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('texte', models.TextField(blank=True)),
                ('enigme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avent2025.enigme')),
            ],
        ),
        migrations.CreateModel(
            name='IndiceDevinette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('texte', models.TextField()),
                ('enigme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avent2025.devinette')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentEnigma', models.IntegerField(default=0)),
                ('erreurEnigma', models.IntegerField(default=0)),
                ('currentDevinette', models.IntegerField(default=0)),
                ('erreurDevinette', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('indices_enigme_reveles', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('indices_devinette_reveles', models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_2025', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
