# Generated by Django 5.1.2 on 2025-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='categorie',
            field=models.CharField(choices=[('ME', 'Mécanique'), ('RE', 'Réponse attendue')], default='ME', max_length=2, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='indicedevinette',
            name='categorie',
            field=models.CharField(choices=[('ME', 'Mécanique'), ('RE', 'Réponse attendue')], default='ME', max_length=2, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='indicedevinette',
            name='texte',
            field=models.TextField(blank=True),
        ),
    ]
