# Generated by Django 5.1.2 on 2025-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0002_indice_categorie_indicedevinette_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='cout',
            field=models.IntegerField(choices=[(1, '1 point'), (2, '2 points'), (3, '3 points')], default=1, verbose_name='Coût en points'),
        ),
        migrations.AddField(
            model_name='indicedevinette',
            name='cout',
            field=models.IntegerField(choices=[(1, '1 point'), (2, '2 points'), (3, '3 points')], default=1, verbose_name='Coût en points'),
        ),
    ]
