# Generated by Django 5.1.2 on 2025-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0003_indice_cout_indicedevinette_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_family',
            field=models.BooleanField(default=False, help_text='Cochez pour marquer cet utilisateur comme membre de la famille', verbose_name='Membre de la famille'),
        ),
    ]
