# Generated by Django 5.1.2 on 2025-11-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0004_userprofile_is_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_enigme_resolue', models.IntegerField(default=100, help_text='Nombre de points gagnés pour chaque énigme résolue', verbose_name='Points par énigme résolue')),
                ('points_devinette_resolue', models.IntegerField(default=10, help_text='Nombre de points gagnés pour chaque devinette résolue', verbose_name='Points par devinette résolue')),
                ('malus_erreur_enigme', models.IntegerField(default=10, help_text='Nombre de points perdus pour chaque mauvaise réponse à une énigme', verbose_name="Malus par erreur d'énigme")),
                ('malus_erreur_devinette', models.IntegerField(default=2, help_text='Nombre de points perdus pour chaque mauvaise réponse à une devinette', verbose_name='Malus par erreur de devinette')),
            ],
            options={
                'verbose_name': 'Configuration des scores',
                'verbose_name_plural': 'Configuration des scores',
            },
        ),
    ]
