# Generated by Django 5.1.2 on 2025-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0005_scoreconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice',
            options={'ordering': ['enigme', 'numero']},
        ),
        migrations.AlterModelOptions(
            name='indicedevinette',
            options={'ordering': ['enigme', 'numero']},
        ),
        migrations.AddField(
            model_name='indice',
            name='type_indice',
            field=models.CharField(choices=[('NO', 'Normal'), ('LC', 'Last Chance')], default='NO', help_text="Normal: disponible immédiatement | Last Chance: débloqué à l'énigme suivante", max_length=2, verbose_name="Type d'indice"),
        ),
        migrations.AddField(
            model_name='indicedevinette',
            name='type_indice',
            field=models.CharField(choices=[('NO', 'Normal'), ('LC', 'Last Chance')], default='NO', help_text='Normal: disponible immédiatement | Last Chance: débloqué à la devinette suivante', max_length=2, verbose_name="Type d'indice"),
        ),
        migrations.AlterField(
            model_name='indice',
            name='cout',
            field=models.IntegerField(choices=[(1, '1 point'), (2, '2 points'), (3, '3 points'), (5, '5 points'), (8, '8 points'), (10, '10 points')], default=1, verbose_name='Coût en points'),
        ),
        migrations.AlterField(
            model_name='indicedevinette',
            name='cout',
            field=models.IntegerField(choices=[(1, '1 point'), (2, '2 points'), (3, '3 points'), (5, '5 points'), (8, '8 points'), (10, '10 points')], default=1, verbose_name='Coût en points'),
        ),
    ]
