# Generated by Django 5.1.2 on 2025-11-21 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0006_alter_indice_options_alter_indicedevinette_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('ENIGME_VIEW', 'Consultation énigme'), ('ENIGME_SUCCESS', 'Énigme réussie'), ('ENIGME_FAIL', 'Énigme échouée'), ('DEVINETTE_VIEW', 'Consultation devinette'), ('DEVINETTE_SUCCESS', 'Devinette réussie'), ('DEVINETTE_FAIL', 'Devinette échouée'), ('INDICE_REVEAL', 'Révélation indice énigme'), ('INDICE_DEV_REVEAL', 'Révélation indice devinette'), ('CLASSEMENT_VIEW', 'Consultation classement'), ('HOME_VIEW', 'Consultation accueil')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('enigme_id', models.IntegerField(blank=True, null=True, verbose_name='ID Énigme')),
                ('devinette_id', models.IntegerField(blank=True, null=True, verbose_name='ID Devinette')),
                ('indice_id', models.IntegerField(blank=True, null=True, verbose_name='ID Indice')),
                ('reponse_donnee', models.CharField(blank=True, max_length=500, verbose_name='Réponse donnée')),
                ('details', models.TextField(blank=True, verbose_name='Détails additionnels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
