# Generated by Django 5.1.2 on 2025-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reponses_devinettes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Réponses validées des devinettes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reponses_enigmes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Réponses validées des énigmes'),
        ),
    ]
