# Generated by Django 5.1.2 on 2025-12-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2025', '0008_userprofile_reponses_devinettes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_cheater',
            field=models.BooleanField(default=False, help_text='Cochez pour marquer cet utilisateur comme tricheur (exclu des classements)', verbose_name='Tricheur détecté'),
        ),
    ]
