# Generated by Django 5.1.15 on 2026-09-30 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("enigme", "Énigme"), ("devinette", "Devinette")],
                        max_length=10,
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        help_text="1 à 24", verbose_name="Jour"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("facile", "Facile"), ("difficile", "Difficile")],
                        default="facile",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Titre")),
                (
                    "text",
                    models.TextField(
                        help_text="HTML autorisé (contenu saisi par l'admin uniquement).",
                        verbose_name="Énoncé",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Optionnel. Garder < 200 Ko (espace disque limité).",
                        upload_to="avent2026/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "answers",
                    models.TextField(
                        help_text="Une par ligne. Comparaison sans accents, majuscules ni ponctuation.",
                        verbose_name="Réponses acceptées",
                    ),
                ),
                (
                    "base_points",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Laisser vide pour utiliser la valeur par défaut (voir scoring.py).",
                        null=True,
                        verbose_name="Points de base",
                    ),
                ),
                (
                    "unlock_date",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide : 1er + jour décembre 2026.",
                        null=True,
                        verbose_name="Date de déblocage",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "kind", "difficulty"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "day", "difficulty"),
                        name="uniq_avent2026_puzzle",
                    ),
                    models.CheckConstraint(
                        check=models.Q(("day__gte", 1), ("day__lte", 24)),
                        name="avent2026_day_1_24",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Numéro"),
                ),
                ("text", models.TextField(verbose_name="Indice")),
                (
                    "cost",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Laisser vide pour la valeur par défaut.",
                        null=True,
                        verbose_name="Coût (points)",
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="avent2026.puzzle",
                    ),
                ),
            ],
            options={
                "ordering": ["puzzle", "number"],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("errors", models.PositiveIntegerField(default=0)),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "points",
                    models.IntegerField(default=0, verbose_name="Points obtenus"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avent2026_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="avent2026.puzzle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HintReveal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revealed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reveals",
                        to="avent2026.hint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avent2026_hints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "hint"), name="uniq_avent2026_reveal"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hint",
            constraint=models.UniqueConstraint(
                fields=("puzzle", "number"), name="uniq_avent2026_hint"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["puzzle", "solved_at"], name="avent2026_a_puzzle__f0f559_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                fields=("user", "puzzle"), name="uniq_avent2026_attempt"
            ),
        ),
    ]
