# Generated by Django 5.1.15 on 2026-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avent2026", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="story",
            field=models.TextField(
                blank=True,
                help_text="Révélé au joueur quand il résout ce puzzle (HTML autorisé).",
                verbose_name="Fragment d'histoire",
            ),
        ),
    ]
