# Generated by Django 5.1.2 on 2024-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0002_userprofile_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('reponse', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currentEnigma',
            field=models.IntegerField(default=0),
        ),
    ]
