# Generated by Django 5.1.2 on 2024-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0003_enigme_alter_userprofile_currentenigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='date_dispo',
            field=models.DateField(default='2024-11-01'),
        ),
        migrations.AddField(
            model_name='enigme',
            name='image_name',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
