# Generated by Django 5.1.2 on 2024-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0004_enigme_date_dispo_enigme_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='date_dispo',
            field=models.DateField(default='2024-11-02'),
        ),
    ]
