# Generated by Django 5.1.2 on 2024-11-18 12:07

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0005_alter_enigme_date_dispo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devinette',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('image_name', models.ImageField(default='', upload_to='uploads')),
                ('reponse', models.CharField(max_length=100)),
                ('date_dispo', models.DateField(default='2024-11-02')),
                ('genre', models.CharField(choices=[('FI', 'Film'), ('CH', 'Chanson'), ('PE', 'Personalité')], default='FI', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='indices_devinette_reveles',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='indices_enigme_reveles',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='uploads')),
                ('texte', models.TextField()),
                ('enigme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avent2024.enigme')),
            ],
        ),
        migrations.CreateModel(
            name='IndiceDevinette',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='uploads')),
                ('texte', models.TextField()),
                ('enigme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avent2024.devinette')),
            ],
        ),
    ]
