# Generated by Django 5.1.2 on 2024-11-18 12:34

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0006_devinette_userprofile_indices_devinette_reveles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='indices_devinette_reveles',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='indices_enigme_reveles',
            field=models.CharField(blank=True, default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
