# Generated by Django 5.1.2 on 2024-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0007_alter_userprofile_indices_devinette_reveles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indice',
            name='numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='indicedevinette',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
