# Generated by Django 5.1.2 on 2024-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0008_indice_numero_indicedevinette_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indicedevinette',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
