# Generated by Django 5.1.2 on 2024-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0009_alter_indice_id_alter_indicedevinette_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinette',
            name='image_name',
            field=models.ImageField(default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='image_name',
            field=models.ImageField(default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='indice',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='indicedevinette',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='uploads'),
        ),
    ]
