# Generated by Django 5.1.2 on 2024-11-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0010_alter_devinette_image_name_alter_enigme_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinette',
            name='image_name',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='image_name',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='indice',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
