# Generated by Django 5.1.2 on 2024-11-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0011_alter_devinette_image_name_alter_enigme_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devinette',
            name='texte',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indice',
            name='texte',
            field=models.TextField(blank=True),
        ),
    ]
