# Generated by Django 5.1.3 on 2024-11-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0012_alter_devinette_texte_alter_indice_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currentDevinette',
            field=models.IntegerField(default=0),
        ),
    ]
