# Generated by Django 5.1.3 on 2024-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0013_userprofile_currentdevinette'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='erreurDevinette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='erreurEnigma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
