# Generated by Django 5.1.3 on 2024-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avent2024', '0014_userprofile_erreurdevinette_userprofile_erreurenigma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicedevinette',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
