# Generated by Django 5.1.2 on 2025-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='Code ISBN du livre', max_length=13, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('authors', models.CharField(max_length=300, verbose_name='Auteur(s)')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Éditeur')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('age_range', models.CharField(blank=True, max_length=50, verbose_name="Tranche d'âge")),
                ('reading_level', models.CharField(blank=True, max_length=50, verbose_name='Niveau de lecture')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires de la maîtresse')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Note (1-5)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='URL de la couverture')),
                ('google_books_id', models.CharField(blank=True, max_length=100, verbose_name='ID Google Books')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['title'],
            },
        ),
    ]
