# Generated by Django 5.1.2 on 2025-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.CharField(blank=True, help_text='Séparez les thèmes par des virgules (ex: aventure, amitié, nature)', max_length=200, verbose_name='Thème(s)'),
        ),
    ]
