# Generated by Django 5.1.2 on 2025-08-14 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Nom d'utilisateur Chess.com", max_length=100)),
                ('game_id', models.CharField(help_text='ID unique de la partie', max_length=50, unique=True)),
                ('game_url', models.URLField(help_text='URL de la partie sur Chess.com')),
                ('white_player', models.CharField(max_length=100)),
                ('black_player', models.CharField(max_length=100)),
                ('time_control', models.CharField(max_length=50)),
                ('rated', models.BooleanField(default=True)),
                ('result', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pgn', models.TextField(help_text='Notation PGN de la partie')),
                ('moves_data', models.JSONField(default=dict, help_text='Données des coups avec évaluations')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analyzed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MoveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move_notation', models.CharField(max_length=10)),
                ('evaluation_before', models.FloatField(blank=True, null=True)),
                ('evaluation_after', models.FloatField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, choices=[('brilliant', 'Brillant'), ('great', 'Excellent'), ('best', 'Meilleur'), ('good', 'Bon'), ('inaccuracy', 'Imprécision'), ('mistake', 'Erreur'), ('blunder', 'Gaffe')], max_length=20, null=True)),
                ('fen_before', models.TextField()),
                ('fen_after', models.TextField()),
                ('best_move', models.CharField(blank=True, max_length=10, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_analyses', to='chessTrainer.chessgame')),
            ],
            options={
                'ordering': ['move_number'],
                'unique_together': {('game', 'move_number')},
            },
        ),
    ]
