# Generated by Django 5.1.2 on 2025-08-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessTrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveanalysis',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_analyses', to='chessTrainer.chessgame'),
        ),
    ]
