# Generated by Django 5.1.2 on 2025-08-18 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessTrainer', '0002_alter_moveanalysis_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Nom d'utilisateur Chess.com", max_length=100, unique=True)),
                ('last_sync_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Dernière synchronisation')),
                ('last_game_end_time', models.DateTimeField(blank=True, help_text='Timestamp de la dernière partie récupérée', null=True)),
                ('total_games_count', models.IntegerField(default=0, help_text='Nombre total de parties connues')),
                ('sync_count', models.IntegerField(default=0, help_text='Nombre de synchronisations effectuées')),
            ],
            options={
                'ordering': ['-last_sync_time'],
            },
        ),
    ]
