# Generated by Django 5.1.2 on 2025-08-20 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessTrainer', '0003_playersyncstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('positions_attempted', models.IntegerField(default=0)),
                ('positions_solved', models.IntegerField(default=0)),
                ('total_improvement_points', models.FloatField(default=0.0)),
                ('difficulty_filter', models.CharField(default='all', max_length=10)),
                ('max_positions', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Joueur qui s'entraîne", max_length=100)),
                ('fen_position', models.TextField(help_text="Position FEN à partir de laquelle l'utilisateur doit jouer")),
                ('player_color', models.CharField(choices=[('white', 'Blanc'), ('black', 'Noir')], max_length=5)),
                ('original_move', models.CharField(help_text='Coup original (erreur) du joueur', max_length=10)),
                ('original_evaluation', models.FloatField(help_text='Évaluation après le coup original')),
                ('best_move', models.CharField(help_text='Meilleur coup recommandé', max_length=10)),
                ('best_evaluation', models.FloatField(help_text='Évaluation après le meilleur coup')),
                ('alternative_moves', models.JSONField(default=list, help_text='Liste des coups alternatifs avec évaluations')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10)),
                ('times_played', models.IntegerField(default=0)),
                ('times_solved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('move_analysis', models.ForeignKey(help_text="Coup d'origine analysé", on_delete=django.db.models.deletion.CASCADE, to='chessTrainer.moveanalysis')),
                ('original_game', models.ForeignKey(help_text="Partie d'origine", on_delete=django.db.models.deletion.CASCADE, to='chessTrainer.chessgame')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('username', 'original_game', 'move_analysis')},
            },
        ),
        migrations.CreateModel(
            name='TrainingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_move', models.CharField(help_text="Coup tenté par l'utilisateur", max_length=10)),
                ('evaluation_after_attempt', models.FloatField(help_text='Évaluation après le coup tenté')),
                ('result_quality', models.CharField(choices=[('perfect', 'Parfait'), ('good', 'Bon'), ('suboptimal', 'Sous-optimal'), ('poor', 'Mauvais'), ('blunder', 'Gaffe')], max_length=10)),
                ('improvement_points', models.FloatField(help_text="Points d'amélioration par rapport au coup original")),
                ('is_better_than_original', models.BooleanField(default=False)),
                ('is_best_move', models.BooleanField(default=False)),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Temps passé à réfléchir (en secondes)')),
                ('training_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='chessTrainer.trainingposition')),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
    ]
