# Generated by Django 5.1.2 on 2025-08-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessTrainer', '0004_trainingsession_trainingposition_trainingattempt'),
    ]

    operations = [
    ]
