# Generated by Django 5.1.2 on 2025-08-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Mot à deviner')),
                ('definition', models.TextField(verbose_name='Définition')),
                ('difficulty', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=2, verbose_name='Difficulté')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Définition',
                'verbose_name_plural': 'Définitions',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la personne')),
                ('image', models.ImageField(upload_to='max_challenge/photos/', verbose_name='Photo')),
                ('ascii_art', models.TextField(blank=True, verbose_name='ASCII Art')),
                ('width', models.IntegerField(default=80, verbose_name='Largeur ASCII')),
                ('height', models.IntegerField(default=40, verbose_name='Hauteur ASCII')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la partie')),
                ('team_a_name', models.CharField(default='Équipe A', max_length=100, verbose_name='Nom équipe A')),
                ('team_b_name', models.CharField(default='Équipe B', max_length=100, verbose_name='Nom équipe B')),
                ('team_a_score', models.IntegerField(default=0, verbose_name='Score équipe A')),
                ('team_b_score', models.IntegerField(default=0, verbose_name='Score équipe B')),
                ('team_a_revealed_chars', models.JSONField(default=list, verbose_name='Caractères révélés équipe A')),
                ('team_b_revealed_chars', models.JSONField(default=list, verbose_name='Caractères révélés équipe B')),
                ('global_revealed_photos', models.JSONField(default=list, verbose_name="Photos révélées dans l'image globale")),
                ('revealed_words', models.JSONField(default=list, verbose_name='Mots révélés de la définition')),
                ('is_active', models.BooleanField(default=True, verbose_name='Partie active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='max_challenge.definition', verbose_name='Définition actuelle')),
                ('global_photos', models.ManyToManyField(related_name='global_games', to='max_challenge.photo', verbose_name="Photos pour l'image globale")),
                ('team_a_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_team_a', to='max_challenge.photo', verbose_name='Photo équipe A')),
                ('team_b_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_team_b', to='max_challenge.photo', verbose_name='Photo équipe B')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
