# Generated by Django 5.1.2 on 2025-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ascii_reveal_speed',
            field=models.CharField(choices=[('slow', 'Lente'), ('medium', 'Moyenne'), ('fast', 'Rapide')], default='medium', max_length=10, verbose_name='Vitesse révélation ASCII'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='definition_reveal_speed',
            field=models.CharField(choices=[('slow', 'Lente'), ('medium', 'Moyenne'), ('fast', 'Rapide')], default='medium', max_length=10, verbose_name='Vitesse révélation définitions'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='max_teams',
            field=models.IntegerField(default=4, verbose_name="Nombre maximum d'équipes"),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='points_per_correct',
            field=models.IntegerField(default=10, verbose_name='Points par bonne réponse'),
        ),
    ]
