# Generated by Django 5.1.2 on 2025-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0002_gamesession_ascii_reveal_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='team_a_photo_revealed',
            field=models.BooleanField(default=False, verbose_name='Photo équipe A révélée'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='team_b_photo_revealed',
            field=models.BooleanField(default=False, verbose_name='Photo équipe B révélée'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=480, verbose_name='Hauteur ASCII'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=240, verbose_name='Largeur ASCII'),
        ),
    ]
