# Generated by Django 5.1.2 on 2025-11-04 16:36

from django.db import migrations, models


def deactivate_old_sessions(apps, schema_editor):
    """Désactive toutes les GameSession sauf la plus récente pour respecter la contrainte d'unicité"""
    GameSession = apps.get_model('max_challenge', 'GameSession')
    active_sessions = GameSession.objects.filter(is_active=True).order_by('-created_at')
    
    if active_sessions.count() > 1:
        # Garde la plus récente active, désactive les autres
        sessions_to_deactivate = active_sessions[1:]
        for session in sessions_to_deactivate:
            session.is_active = False
            session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0003_gamesession_team_a_photo_revealed_and_more'),
    ]

    operations = [
        migrations.RunPython(deactivate_old_sessions, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_game_session'),
        ),
    ]
