# Generated by Django 5.1.2 on 2025-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0004_gamesession_unique_active_game_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_revealed_word',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Dernier mot révélé'),
        ),
    ]
