# Generated by Django 5.1.2 on 2025-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0005_gamesession_last_revealed_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='global_revealed_photos',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='team_a_revealed_chars',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='team_b_revealed_chars',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='ascii_art',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='width',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='team_a_revealed_squares',
            field=models.JSONField(default=list, verbose_name='Carrés révélés équipe A (0-99)'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='team_b_revealed_squares',
            field=models.JSONField(default=list, verbose_name='Carrés révélés équipe B (0-99)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_400x400',
            field=models.ImageField(blank=True, upload_to='max_challenge/photos_400/', verbose_name='Image 400x400'),
        ),
    ]
