# Generated by Django 5.1.2 on 2025-11-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0006_remove_gamesession_global_revealed_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='used_definitions',
            field=models.JSONField(default=list, verbose_name='IDs des définitions déjà utilisées'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='used_photos',
            field=models.JSONField(default=list, verbose_name='IDs des photos déjà utilisées'),
        ),
    ]
