# Generated by Django 5.1.2 on 2025-11-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0007_gamesession_used_definitions_gamesession_used_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_400x400',
            field=models.ImageField(blank=True, upload_to='max_challenge/photos_400/', verbose_name='Image redimensionnée'),
        ),
    ]
