# Generated by Django 5.1.2 on 2025-11-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_challenge', '0008_alter_photo_image_400x400'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='squares_per_reveal',
            field=models.IntegerField(default=6, verbose_name='Nombre de carrés révélés par tour'),
        ),
    ]
